### ISSUE TITLE
Metadata unsupported attribute "naming_rules = module.naming.yaml"

### ISSUE THREAD

**Issue by eduardodfmex** [Azure-Terraform/terraform-azurerm-metadata#13]
Im having this error using the metadata module

 Error: Unsupported attribute
│
│   on main.tf line 44, in module "metadata":
│   44:   naming_rules = module.naming.yaml
│     ├────────────────
│     │ module.naming is a object
│
│ This object does not have an attribute named "yaml".

Line 44 use naming_rules, this is the module:

`module "metadata" {
  source = "github.com/Azure-Terraform/terraform-azurerm-metadata.git?ref=v1.5.2"

  naming_rules = module.naming.yaml

  market              = "us"
  project             = "https://github.com/Azure-Terraform/terraform-azurerm-storage-account/tree/main/example"
  location            = "eastus2"
  environment         = "sandbox"
  product_name        = random_string.random.result
  business_unit       = "infra"
  product_group       = "contoso"
  subscription_id     = module.subscription.output.subscription_id
  subscription_type   = "dev"
  resource_group_type = "app"
}
`

**Comment by fabiendelpierre** [comment]
Hello,

You may want to look at the included example on how to use this module: [main.tf](https://github.com/Azure-Terraform/terraform-azurerm-metadata/blob/master/example/main.tf)

Note we use this module internally but opted to share it publicly. So it works in ways that you might find are unsuited to your own needs. In the example, you'll see that it refers to a "naming" module, and that provides one of the required inputs to this module. We have an example naming module here: https://github.com/Azure-Terraform/example-naming-template. That module provides a list of pre-validated names to this module in YAML format.
